// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"database/sql"
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	web2 "webookApp/internal/article/handler"
	repository2 "webookApp/internal/article/repository"
	cache3 "webookApp/internal/article/repository/cache"
	dao3 "webookApp/internal/article/repository/mysql"
	service3 "webookApp/internal/article/service"
	"webookApp/internal/background"
	"webookApp/internal/code/SDK/memory"
	"webookApp/internal/code/rateLimiterSMS"
	cache2 "webookApp/internal/code/repository/cache"
	dao2 "webookApp/internal/code/repository/mysql"
	"webookApp/internal/code/service"
	web5 "webookApp/internal/feed/handler"
	cache6 "webookApp/internal/feed/repository/cache"
	dao4 "webookApp/internal/feed/repository/mysql"
	service6 "webookApp/internal/feed/service"
	web4 "webookApp/internal/follow/handler"
	cache5 "webookApp/internal/follow/repository/cache"
	dao6 "webookApp/internal/follow/repository/mysql"
	service5 "webookApp/internal/follow/service"
	web3 "webookApp/internal/like/handler"
	cache4 "webookApp/internal/like/repository/cache"
	dao5 "webookApp/internal/like/repository/mysql"
	service4 "webookApp/internal/like/service"
	"webookApp/internal/sse"
	"webookApp/internal/usr/handler"
	"webookApp/internal/usr/repository"
	"webookApp/internal/usr/repository/cache"
	"webookApp/internal/usr/repository/mysql"
	service2 "webookApp/internal/usr/service"
	"webookApp/wire/article"
	"webookApp/wire/baseconfig"
	"webookApp/wire/follow"
	"webookApp/wire/like"
)

// Injectors from wire.go:

// 顶层 wire 构建
func InitializeApp() (*App, error) {
	viper, err := baseconwire.InitViper()
	if err != nil {
		return nil, err
	}
	zapLogger, err := baseconwire.NewZapLogger(viper)
	if err != nil {
		return nil, err
	}
	client := baseconwire.InitRedis(viper)
	redisSlidingWindowLimiter := baseconwire.NewRateLimiter(viper, client)
	store := baseconwire.NewSessionStore(viper)
	sessionJwt, err := baseconwire.NewSessionJwt(viper)
	if err != nil {
		return nil, err
	}
	engine := baseconwire.NewGinEngine(zapLogger, viper, redisSlidingWindowLimiter, store, sessionJwt)
	db, err := baseconwire.InitMySQL(viper)
	if err != nil {
		return nil, err
	}
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserRedisCache(client)
	userRepository := repository.NewUserRepository(userDao, userCache)
	codeCache := cache2.NewCodeCache(client)
	codeDao := dao2.NewCodeDao(db)
	smsMemory := memory.NewSmsMemory()
	smsServiceDecorator := code.NewSMSServiceDecorator(redisSlidingWindowLimiter, smsMemory)
	codeService := service.NewCodeService(codeCache, codeDao, smsServiceDecorator)
	userService := service2.NewUserService(userRepository, codeService, sessionJwt)
	userHandler := web.NewUser(userService)
	articalDao := dao3.NewArticalDao(db)
	articleCache := cache3.NewArticalCache(client)
	articalRepository := repository2.NewArticalRepository(articalDao, articleCache)
	ossServer := articlewire.NewOssClient(viper)
	snowFlaker := baseconwire.NewSnowFlake(viper)
	articalService := service3.NewArticalService(articalRepository, ossServer, snowFlaker)
	articalHandler := web2.NewArticalHander(articalService)
	likeCache := cache4.NewLikeCache(client)
	likeProducer := likewire.NewLikeProducer(viper, client)
	sseManagerHandler := sse.NewSSEManagerHandler()
	likeService := service4.NewLikeService(likeCache, likeProducer, sseManagerHandler)
	likeHandler := web3.NewLikeHandler(likeService)
	followCache := cache5.NewFollowCache(client)
	followProducer := followwire.NewFollowProducer(viper, client)
	followService := service5.NewFollowService(followCache, followProducer, sseManagerHandler)
	followHandler := web4.NewFollowHandler(followService)
	feeddao := dao4.NewFeedDao(db)
	feedCache := cache6.NewFeedCache(client)
	feedService := service6.NewFeedService(feeddao, feedCache)
	feedHandler := web5.NewFeedHandler(feedService)
	likeSyncer := bgService.ProvideLikeSyncer(db, client)
	followSyncer := bgService.ProvideFollowSyncer(db, client)
	likeDao := dao5.NewLikeDao(db)
	likeMqConsumerAllConfig := likewire.NewLikeConsumerConfig(viper, client)
	likeConsumer := bgService.ProvideLikeConsumer(likeDao, likeMqConsumerAllConfig)
	followDao := dao6.NewFollowDao(db)
	followConsumerAllConfig := followwire.NewFollowConsumerConfig(viper, client)
	followConsumer := bgService.ProvideFollowConsumer(followDao, followConsumerAllConfig)
	async := bgService.ProviderSMSSyncer(viper, db, smsMemory)
	backgroundService := bgService.ProvideBackgroundServices(likeSyncer, followSyncer, likeConsumer, followConsumer, async)
	app := NewApp(engine, userHandler, articalHandler, likeHandler, followHandler, feedHandler, sseManagerHandler, backgroundService, db, client)
	return app, nil
}

// wire.go:

// App 包含所有组件
type App struct {
	Engine           *gin.Engine
	UserHandler      *web.UserHandler
	ArticleHandler   *web2.ArticalHandler
	LikeHandler      *web3.LikeHandler
	FollowHandler    *web4.FollowHandler
	SseHandler       *sse.SSEManagerHandler
	BackgroundSyncer bgService.BackgroundService // 或者单独包含 syncer
	Cleanup          func()                      // 组合所有清理函数
}

func NewApp(
	engine *gin.Engine,
	userHandler *web.UserHandler,
	articleHandler *web2.ArticalHandler,
	likeHandler *web3.LikeHandler,
	followHandler *web4.FollowHandler,
	feedHandler *web5.FeedHandler,
	sseHandler *sse.SSEManagerHandler,
	bgApp bgService.BackgroundService,
	db *sql.DB,
	rds *redis.Client,

) *App {

	userHandler.RegisterRoutes(engine)
	articleHandler.RegisterRoute(engine)
	likeHandler.RegisterRoute(engine)
	followHandler.RegisterRoute(engine)
	feedHandler.RegisterRoute(engine)
	sseHandler.RegisterRoute(engine)

	cleanup := func() {
		for _, i := range bgApp {
			i.Stop()
		}
		db.Close()
		rds.Close()
	}
	return &App{
		Engine:           engine,
		UserHandler:      userHandler,
		ArticleHandler:   articleHandler,
		LikeHandler:      likeHandler,
		FollowHandler:    followHandler,
		SseHandler:       sseHandler,
		BackgroundSyncer: bgApp,
		Cleanup:          cleanup,
	}
}
